sudo: required

language: python

services:
  - docker

before_install:
  # Debugging
  - echo Current path
  - pwd
  - echo Project dir contents
  - ls
  # Build docker image
  - docker build -t test_image -f test/Dockerfile .

script:
  # Run tests
  - docker run test_image -c "python test/travis_test_script.py test/autotest_bot.py"